server:
  port: 8080
#  servlet:
#    context-path: /identity
spring:
  application:
    name : studySpring
  main:
    lazy-initialization: true     # Chỉ khởi tạo các bean khi cần
  datasource:
    url: "jdbc:mysql://localhost:3306/studyspring"
    username: root
    password: quannguyen2004
#  security:
#    user:
#      name: admin
#      password: admin
  jpa:
    hibernate.ddl-auto: update
#    show-sql: true
#      driver-class-name: com.mysql.cj.jdbc.Driver
#logging:
#  level:
#    org.hibernate.SQL: DEBUG

jwt:
  signerKey: "d3+MtWAFiL3bhiALgkfeMQeWFT3sa7krhWp/HLYh0SrB4jlXf0MKd8IDI4B6hDM1\n"
  valid-duration: 60 # Thời hạn của 1 token  # seconds
  refreshable-duration: 120 # seconds  # Thời gian refresh token



 